language: node_js
node_js:
    - "10.15.3"

before_script:
    - yarn
script:
    - yarn lint
    - yarn test

cache:
    directories:
        -node_modules
branches:
    only:
        - master
notifications:
  email:
    on_success: never